### ISSUE TITLE
How to include shader parameters?

### ISSUE THREAD

**Issue by daninthemix** [tyrells/dosbox-svn-shaders#4]
This is great - I dropped in Lottes and added glshader=crt-lottes.glsl to the DOSBox.conf and it just works.

But how do I ditch the screen curvature, for example?

Thanks

**Comment by tyrells** [comment]
Hi @daninthemix. Shader parameters are usually set by a number of `#define` statements in the code. For crt-lottes.glsl these are lines 118-130. The define itself will show the variable name, which you can match to the `#pragma` names at the top of the shader file for a slightly more descriptive name. These `#pragma` lines also show the default, min, max, and step values for the parameter. 

Note: the actual value used by the shader needs to be changed on the `#define` line and **not** the `#pragma` line.

To change the curvature for crt-lottes.glsl you can adjust the `warpX` and `warpY` parameters on lines 120-121. Changing these values to both be 0.0 will remove any curvature effects.

Each shader is written differently, so you may need to play around with changing different parameters values until you find the ones that work best for you.
