### ISSUE TITLE
`crt-lottes.tweaked` breaks with NPOT texture

### ISSUE THREAD

**Issue by GranMinigun** [tyrells/dosbox-svn-shaders#9]
Back in October, DOSBox Staging changed texture creation process: when hardware is able to handle non-power-of-two textures (basically anything that can run shaders at all), the texture is generated with the same dimensions as emulated resolution instead of closest power-of-two. This, combined with clamping to edge, was done to eliminate tiny black border around output, visible with bilinear-filtered output and accentuated with bicubic interpolation.

Unfortunately, `crt-lottes.tweaked.glsl` shader didn't like that change for whatever reason: it now cuts bottom and right sides of the output. We don't have any shader experts on our team, so maybe you could tell what went wrong and possibly patch the shader?

![Screenshot_20211222_202540](https://user-images.githubusercontent.com/11149380/147117113-d9722e48-3a1b-4e92-8e10-4171ef1ceeec.png)

**Comment by tyrells** [comment]
Hi @GranMinigun. Can you confirm the following for me:
- Version of DOSBox Staging being used
- Copy of `dosbox-staging.conf` contents
- Does the error occur in full screen, windowed or both?
- Window size (or screen resolution)
- Does the same error occur for any of the other shaders (e.g. `crt-lottes.glsl`)

**Comment by GranMinigun** [comment]
Development version, anything between somewhere in October to 23 December. After that a workaround has been implemented, which reverts behaviour for shaders (https://github.com/dosbox-staging/dosbox-staging/commit/09c07d1a9e0b3099c7685e1459f01a906be001cf). Default configuration, only shader is set. Occurs both in windowed and fullscreen modes. Window size and resolution do not matter. That specific issue occurs only with that shader, as far as I can tell.

**Comment by tyrells** [comment]
I have updated the base shader to the latest available version, which seems to have fixed the texture issues. Please test and let me know if this works for you.

**Comment by GranMinigun** [comment]
Yeah, that issue is gone. Thanks.
